# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Cool\Cool\Python stuff\QTmaybe\twitterreplygui\untitled3.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import main
import json

class Ui_Form2(object):
    
    
    def addnametojson(self):
        try:
            usernametoadd = self.lineEdit.text()

            f = open("config.json")
            data  = json.load(f)
            data["usernameList"].append(usernametoadd)
            with open("config.json","w") as outfile:
                json.dump(data,outfile)           
           
        except Exception as e:
            print(e)    
    
    def setupUi3(self, Form):
        Form.setObjectName("Form")
        Form.resize(402, 88)
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(20, 10, 361, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(140, 50, 121, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.addnametojson)
        
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Add New"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Enter a Username"))
        self.pushButton.setText(_translate("Form", "Add"))
